# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapchatCloneFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapchatCloneFirebase
pod 'ImageSlideshow', '~> 1.9.0'
pod "ImageSlideshow/Kingfisher"

end
